# Generated by Django 6.1.1 on 2026-09-26 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0003_favorite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["user", "name"], name="collection__user_id_441ddb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dress",
            index=models.Index(
                fields=["user", "-created_at"], name="collection__user_id_5432d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dress",
            index=models.Index(
                fields=["user", "category"], name="collection__user_id_b4ee9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dress",
            index=models.Index(
                fields=["user", "color"], name="collection__user_id_065aad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dress",
            index=models.Index(
                fields=["user", "size"], name="collection__user_id_25a629_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="favorite",
            index=models.Index(
                fields=["user", "-created_at"], name="collection__user_id_9386f4_idx"
            ),
        ),
    ]
